inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'scripts/vendor/**/*'
    - 'platform-tests/src/platform/vendor/**/*'
    - 'platform-tests/example-apps/healthcheck/vendor/**/*'
    - 'tools/metrics/vendor/**/*'

Layout/ArgumentAlignment:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/HashEachMethods:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
