# Source: bosh-exporter
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: BoshStemcellsNotInSync
    rules:
      - alert: BoshStemcellsNotInSync
        expr: "count (count by (bosh_stemcell_version) (bosh_deployment_stemcell_info)) == 1"
        for: 12h
        labels:
          severity: warning
        annotations:
          summary: "Bosh deployment stemcell versions are not in sync"
          description: "The three bosh deployments should have the same stemcell version. If this alert fires then either deploys are taking a long time or the most recent deploys of paas-bootstrap and paas-cf specified different stemcell versions"
