# Source: paas-metrics
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: RDSDBInstancesCountCloseToQuota
    rules:
      - alert: RDSDBInstancesCountCloseToQuota
        expr: ((paas_aws_rds_dbinstances_count / paas_aws_rds_dbinstances_quota_count) * 100) > 80
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Number of AWS RDS DB instances is close to the quota"
          description: "We are using {{ $value | printf \"%.0f\" }}% of the RDS DB instance quota. We might have to increase the quota."
          url: "https://console.aws.amazon.com/servicequotas/home?region=((aws_region))#!/services/rds/quotas/L-7B6409FD"
