buildpacks:
- name: binary_buildpack
  repo_name: binary-buildpack
  stack: cflinuxfs3
  version: v1.0.36
  sha: 8bf473f805b9e8deff6f58d57533737d6afe02fa3ad6a27073e73e100b2b0937
  filename: binary-buildpack-cflinuxfs3-v1.0.36.zip
  url: https://github.com/cloudfoundry/binary-buildpack/releases/download/v1.0.36/binary-buildpack-cflinuxfs3-v1.0.36.zip
  dependencies: []
- name: dotnet_core_buildpack
  repo_name: dotnet-core-buildpack
  stack: cflinuxfs3
  version: v2.3.22
  sha: eaaa7464dd21afc36b5522b0d2cbd595d71ca4c28ff7a881e7d8d0aa5be2cac2
  filename: dotnet-core-buildpack-cflinuxfs3-v2.3.22.zip
  url: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v2.3.22/dotnet-core-buildpack-cflinuxfs3-v2.3.22.zip
  dependencies:
  - name: bower
    version: 1.8.12
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.23
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.24
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.10
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.11
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 5.0.1
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 5.0.2
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.23
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.24
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.10
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.11
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 5.0.1
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 5.0.2
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.811
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.812
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.404
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.405
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 5.0.101
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 5.0.102
    cf_stacks:
    - cflinuxfs3
  - name: libgdiplus
    version: "6.0"
    cf_stacks:
    - cflinuxfs3
  - name: libunwind
    version: "1.5"
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.23.2
    cf_stacks:
    - cflinuxfs3
- name: go_buildpack
  repo_name: go-buildpack
  stack: cflinuxfs3
  version: v1.9.25
  sha: 97264265e60b8ee0672b66cec26b69f87cb0d5f19b1fb3f743284bcd47bfa441
  filename: go-buildpack-cflinuxfs3-v1.9.25.zip
  url: https://github.com/cloudfoundry/go-buildpack/releases/download/v1.9.25/go-buildpack-cflinuxfs3-v1.9.25.zip
  dependencies:
  - name: dep
    version: 0.5.4
    cf_stacks:
    - cflinuxfs3
  - name: glide
    version: 0.13.3
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.14.13
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.14.14
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.15.6
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.15.7
    cf_stacks:
    - cflinuxfs3
  - name: godep
    version: "80"
    cf_stacks:
    - cflinuxfs3
- name: java_buildpack
  repo_name: java-buildpack
  stack: cflinuxfs3
  version: v4.36
  sha: 82aa711138298285cd66f7e9ca3ca4867ce7d8f286a78580bf83733df114e3a6
  filename: java-buildpack-v4.36.zip
  url: https://github.com/cloudfoundry/java-buildpack/releases/download/v4.36/java-buildpack-v4.36.zip
  dependencies: []
- name: nodejs_buildpack
  repo_name: nodejs-buildpack
  stack: cflinuxfs3
  version: v1.7.41
  sha: e588fd18ba0cebf8b3c1d0055084ed0fcba04cc42f40031b94a9dbd7901747e7
  filename: nodejs-buildpack-cflinuxfs3-v1.7.41.zip
  url: https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.7.41/nodejs-buildpack-cflinuxfs3-v1.7.41.zip
  dependencies:
  - name: node
    version: 10.23.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.23.2
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.20.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.20.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 14.15.3
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 14.15.4
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 15.5.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 15.7.0
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.10
    cf_stacks:
    - cflinuxfs3
- name: php_buildpack
  repo_name: php-buildpack
  stack: cflinuxfs3
  version: v4.4.30
  sha: 3c0937f1728483749d362e06595b3c01d9af71b10642994762832890a9ac6e04
  filename: php-buildpack-cflinuxfs3-v4.4.30.zip
  url: https://github.com/cloudfoundry/php-buildpack/releases/download/v4.4.30/php-buildpack-cflinuxfs3-v4.4.30.zip
  dependencies:
  - name: CAAPM
    version: 20.11.0
    cf_stacks:
    - cflinuxfs3
  - name: appdynamics
    version: 20.4.0.3759
    cf_stacks:
    - cflinuxfs3
  - name: composer
    version: 2.0.9
    cf_stacks:
    - cflinuxfs3
  - name: httpd
    version: 2.4.46
    cf_stacks:
    - cflinuxfs3
  - name: newrelic
    version: 9.14.0.290
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.18.0
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.19.6
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.25
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.26
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.13
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.14
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 8.0.1
    cf_stacks:
    - cflinuxfs3
- name: python_buildpack
  repo_name: python-buildpack
  stack: cflinuxfs3
  version: v1.7.29
  sha: db9b27b550e6a968283bf4e6cd3f8cf01a49bb008498c5714726ad481f4dc8fa
  filename: python-buildpack-cflinuxfs3-v1.7.29.zip
  url: https://github.com/cloudfoundry/python-buildpack/releases/download/v1.7.29/python-buildpack-cflinuxfs3-v1.7.29.zip
  dependencies:
  - name: libffi
    version: 3.2.1
    cf_stacks:
    - cflinuxfs3
  - name: libmemcache
    version: 1.0.18
    cf_stacks:
    - cflinuxfs3
  - name: miniconda3
    version: 4.7.12.1
    cf_stacks:
    - cflinuxfs3
  - name: miniconda37
    version: 4.9.2
    cf_stacks:
    - cflinuxfs3
  - name: miniconda38
    version: 4.9.2
    cf_stacks:
    - cflinuxfs3
  - name: pip-pop
    version: 0.1.5
    cf_stacks:
    - cflinuxfs3
  - name: pipenv
    version: 2020.11.15
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.11
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.12
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.8
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.6
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.7
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.9.0
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.9.1
    cf_stacks:
    - cflinuxfs3
  - name: setuptools
    version: 52.0.0
    cf_stacks:
    - cflinuxfs3
- name: ruby_buildpack
  repo_name: ruby-buildpack
  stack: cflinuxfs3
  version: v1.8.30
  sha: e3b0368fffb66d0881ec8a0aeea2410343208876f9eb50aa500c9ee7bc27dc16
  filename: ruby-buildpack-cflinuxfs3-v1.8.30.zip
  url: https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.8.30/ruby-buildpack-cflinuxfs3-v1.8.30.zip
  dependencies:
  - name: bundler
    version: 1.17.3
    cf_stacks:
    - cflinuxfs3
  - name: bundler
    version: 2.2.7
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.1.17.0
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.2.14.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.23.2
    cf_stacks:
    - cflinuxfs3
  - name: openjdk1.8-latest
    version: 1.8.0
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.7
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.8
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.5
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.6
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.7.1
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.7.2
    cf_stacks:
    - cflinuxfs3
  - name: rubygems
    version: 3.2.7
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.10
    cf_stacks:
    - cflinuxfs3
- name: staticfile_buildpack
  repo_name: staticfile-buildpack
  stack: cflinuxfs3
  version: v1.5.15
  sha: 8d69194b4bfd8fb6e5ee7d24f06b66c19a678557e3a9bd3744f9d695866a46c1
  filename: staticfile-buildpack-cflinuxfs3-v1.5.15.zip
  url: https://github.com/cloudfoundry/staticfile-buildpack/releases/download/v1.5.15/staticfile-buildpack-cflinuxfs3-v1.5.15.zip
  dependencies:
  - name: nginx
    version: 1.19.6
    cf_stacks:
    - cflinuxfs3
- name: nginx_buildpack
  repo_name: nginx-buildpack
  stack: cflinuxfs3
  version: v1.1.20
  sha: 659315b0035a4677d44421b582ca99558bae68d34be26d4f476777a0cc068600
  filename: nginx-buildpack-cflinuxfs3-v1.1.20.zip
  url: https://github.com/cloudfoundry/nginx-buildpack/releases/download/v1.1.20/nginx-buildpack-cflinuxfs3-v1.1.20.zip
  dependencies:
  - name: nginx
    version: 1.18.0
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.19.6
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.13.6.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.15.8.3
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.17.8.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.19.3.1
    cf_stacks:
    - cflinuxfs3
- name: r_buildpack
  repo_name: r-buildpack
  stack: cflinuxfs3
  version: v1.1.11
  sha: d963b4b6e08f0eae641f5f3612c6f69b6f79f72453a7519eb19e03cc847f8476
  filename: r-buildpack-cflinuxfs3-v1.1.11.zip
  url: https://github.com/cloudfoundry/r-buildpack/releases/download/v1.1.11/r-buildpack-cflinuxfs3-v1.1.11.zip
  dependencies:
  - name: r
    version: 3.6.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.3
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 4.0.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 4.0.3
    cf_stacks:
    - cflinuxfs3
