- type: replace
  path: /releases/-
  value:
    name: caddy
    version: "0.7.0"
    url: "https://bosh.io/d/github.com/dpb587/caddy-bosh-release?v=0.7.0"
    sha1: "3602cd1a33f6d6ac49175b70db6ce6b96fa84e20"

- type: replace
  path: /releases/-
  value:
    name: observability
    version: 0.1.7
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/observability-0.1.7.tgz
    sha1: a066c69960410764cf0a2eb8bfb20ea22eec0250

- type: replace
  path: /variables/-
  value:
    name: paas_admin_prometheus_password
    type: password

- type: replace
  path: /variables/-
  value:
    name: custom_broker_acceptance_prometheus_password
    type: password

- type: replace
  path: /instance_groups/-
  value:
    name: prometheus
    instances: 1
    azs: [z1, z2, z3]
    stemcell: default

    persistent_disk_type: 100GB
    vm_type: small

    networks:
      - name: cf

    jobs:
      - name: prometheus2
        release: prometheus
        properties:
          prometheus:
            rule_files: []

            scrape_configs:
              - job_name: prometheus
                static_configs:
                  - targets: [localhost:9090]

              - job_name: aiven
                scheme: https

                basic_auth:
                  username: ((aiven_prometheus_username))
                  password: ((aiven_prometheus_password))

                tls_config:
                  insecure_skip_verify: true

                file_sd_configs:
                  - refresh_interval: 15s
                    files:
                      - /var/vcap/store/aiven-service-discovery/discovery/targets.json

                relabel_configs:
                  - source_labels: [__address__]
                    separator: ;
                    regex: (.*)
                    target_label: __address__
                    replacement: ${1}:9273
                    action: replace

      - name: route_registrar
        release: routing
        properties:
          route_registrar:
            routes:
              - name: prometheus
                port: 8080
                prepend_instance_index: false
                registration_interval: 10s
                uris:
                  - prometheus.((system_domain))

      - name: caddy
        release: caddy
        properties:
          http_port: 8080
          caddyfile: |
            http://:8080 {
              tls off

              basicauth / paas-admin ((paas_admin_prometheus_password))
              basicauth / custom-broker-acceptance ((custom_broker_acceptance_prometheus_password))

              proxy / http://q-s3-i0.prometheus.*.((environment)).bosh:9090 http://localhost:9090 {
                policy first
                fail_timeout 10s
                max_fails 5
                try_duration 2.5s
                try_interval 100ms
                health_check /-/ready
                health_check_interval 10s
                health_check_timeout 2.5s
                health_check_contains Ready
                timeout 30s
                except /-/reload
              }
            }

      - name: aiven-service-discovery
        release: observability
        properties:
          aiven:
            project: paas-cf-((aws_account))
            api_token: ((aiven_api_token))
            prometheus_endpoint_id: ((aiven_prometheus_endpoint_id))

          target_path: /var/vcap/store/aiven-service-discovery/discovery
          target_filename: targets.json
