---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ghcr.io/alphagov/paas/cf-acceptance-tests
    tag: 54495aab0a18ba76a55d98ae19f904d3629feb77

run:
  path: sh
  args:
  - -e
  - -c
  - |
    curl -m 10 "https://cronitor.link/${CRONITOR_SMOKE_TEST_MONITOR_CODE}/${CRONITOR_MONITOR_PING_ENDPOINT}?host=${DEPLOY_ENV}&series=${CCI_BUILD_NUMBER}&message=${CRONITOR_PING_MESSAGE}" || true

