platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/alphagov/paas/bosh-cli-v2
    tag: 54495aab0a18ba76a55d98ae19f904d3629feb77


run:
  path: sh
  args:
    - -e
    - -c
    - |
      credhub login
      credhub generate --name "$DESTINATION" --type ssh
      credhub get --name "$DESTINATION" --key public_key
