---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/bosh-cli-v2
    tag: cf791cec329bff5577cd8b3c9511bf89f988b5d4
inputs:
  - name: paas-cf
  - name: admin-creds
outputs:
  - name: test-config
run:
  path: sh
  args:
    - -e
    - -c
    - |
      bosh interpolate --var-errs \
        --var=admin_user="$(cat admin-creds/username)" \
        --var=admin_password="$(cat admin-creds/password)" \
        --var=system_domain="${SYSTEM_DOMAIN}" \
        --var=app_domain="${APP_DOMAIN}" \
        --var=name_prefix="${NAME_PREFIX:-CATS}" \
        --var=secrets_test_user_password="${TEST_USER_PASSWORD}" \
        "paas-cf/manifests/cf-manifest/test-config/${TEST_PROPERTIES}.yml" | \
          ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(STDIN))' > test-config/config.json
