---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ghcr.io/alphagov/paas/ruby
    tag: b11f2b9068cd492ffd3b33b9db54a1cf8ad136b3
inputs:
  - name: paas-cf
  - name: cf-manifest
outputs:
  - name: config
run:
  path: sh
  args:
    - -e
    - -u
    - -c
    - |
      cat << EOT > config/config.sh
      export CF_ADMIN=admin
      export CF_PASS=((cf_pass))
      export API_ENDPOINT=((api_endpoint))

      EOT

      . ./config/config.sh
      echo "API_ENDPOINT: ${API_ENDPOINT}"
